### ISSUE TITLE
Error: The stack named MailDog-production failed creation, it may need to be manually deleted from the AWS console

### ISSUE THREAD

**Issue by Logerfo** [edmundhung/maildog#10]
See: https://github.com/Logerfo/maildog/runs/3069195853?check_suite_focus=true#step:9:180

**Comment by edmundhung** [comment]
Hi Logerfo. Thanks for giving `maildog` a try. 
As you mentioned on https://github.com/edmundhung/maildog/issues/7, could you try removing the comment from the json config and push for a redeploy? It would probably fix itself.

I will be around and help if it doesn't work :-)

**Comment by edmundhung** [comment]
@Logerfo 
I just read the log again. It looks like you put a `space` in the alias which makes it an invalid email address. Maybe you can fix it by removing the space on the alias name

**Comment by Logerfo** [comment]
It worked. Thanks!
