### ISSUE TITLE
Typo in the "How it works" illustration

### ISSUE THREAD

**Issue by cuu508** [edmundhung/maildog#4]
Hello, 

In the "How it works" illustration, Lambda is misspelled as Lamda in one place:

![image](https://user-images.githubusercontent.com/661859/125464824-ea4320df-ed03-431e-b851-5600df6703b1.png)

**Comment by edmundhung** [comment]
Good catch @cuu508, thanks! 
I am just working on an update of the diagram as it seems not clear to many people.
I will make sure it is fixed together :smile:
