### ISSUE TITLE
Specifying the remote

### ISSUE THREAD

**Issue by Logerfo** [edmundhung/maildog#8]
On the installation guide, `gh` commands won't really work out of the box, unless I specify the argument `-R logerfo/maildog`. Otherwise, it would try to run it on the original repository (this one), which I don't have permission to. There's probably a command to make my repository the default, but I don't know. It would be nice to have this on the guide.

**Comment by edmundhung** [comment]
Thanks for letting me know. I was actually having a similar problem when I set it up on an organization and thought it only happens to the organization repository. Let me take a look at the `gh` docs and see if it is possible to change or set a default.
